export const decks: DataCard[] = [
	{
		simpleID: "a",
		name: "Padrão",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
	{
		simpleID: "s",
		name: "Matemática",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
	{
		simpleID: "d",
		name: "Biologia",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
	{
		simpleID: "f",
		name: "Química",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
	{
		simpleID: "g",
		name: "Japonês",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
	{
		simpleID: "h",
		name: "Inglês",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
	{
		simpleID: "j",
		name: "Curitiba",
		new: 10,
		wrong: 10,
		review: 20,
		description: "descrição",
		intervalModifierRate: 1,
		createdAt: new Date(),
		startEaseRate: 2,
		hardIntervalRate: 1,
		easyBonusRate: 1,
		newCardsLimit: 10,
		reviewCardsLimit: 20,
		orderType: "random",
	},
]
